[phases.setup]
nixPkgs = ['nodejs', 'python3']
aptPkgs = ['build-essential', 'libudev-dev']

[build]
builder = "NIXPACKS"
buildCommand = "pnpm run build"

[deploy]
startCommand = "pnpm run prisma-db-push && pnpm --filter ./apps/backend run start"
