[phases.setup]
nixPkgs = ['nodejs', 'python3']
aptPkgs = ['build-essential', 'libudev-dev']

[build]
builder = "NIXPACKS"
buildCommand = 'if [ "$POSTIZ_ROLE" = "frontend" ]; then pnpm --filter ./apps/frontend run build; else pnpm --filter ./apps/backend --filter ./apps/orchestrator run build; fi'

[deploy]
startCommand = 'if [ "$POSTIZ_ROLE" = "frontend" ]; then pnpm --filter ./apps/frontend exec next start -p ${PORT:-4200}; else pnpm run prisma-db-push && pnpm --filter ./apps/backend --filter ./apps/orchestrator --parallel start; fi'
