[phases.setup]
nixPkgs = ['nodejs', 'python3']
aptPkgs = ['build-essential', 'libudev-dev']

[phases.build]
commands = ["pnpm run build"]

[phases.deploy]
startCommand = "pnpm --filter ./apps/backend run start"
